version: "3.8"

x-refs:
  restart: &restart
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      rollback_config:
        parallelism: 2
      update_config:
        parallelism: 2

volumes:
  db:
  events:
  geoip:

services:
  mail:
    image: bytemark/smtp
    <<: *restart

  db:
    image: postgres:12
    <<: *restart
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:

  events:
    image: yandex/clickhouse-server:21.3.2.5
    <<: *restart
    volumes:
      - events:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  geoip:
    image: maxmindinc/geoipupdate
    environment:
      GEOIPUPDATE_EDITION_IDS: GeoLite2-Country
      GEOIPUPDATE_FREQUENCY: "168"
      GEOIPUPDATE_ACCOUNT_ID:
      GEOIPUPDATE_LICENSE_KEY:
    volumes:
      - geoip:/usr/share/GeoIP

  plausible:
    image: plausible/analytics:latest
    <<: *restart
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - db
      - events
      - mail
      - geoip
    ports:
      - 8077:8000
    environment:
      GEOLITE2_COUNTRY_DB: /geoip/GeoLite2-Country.mmdb
      DISABLE_REGISTRATION: "true"
      DATABASE_URL:
      CLICKHOUSE_DATABASE_URL:
      ADMIN_USER_EMAIL:
      ADMIN_USER_NAME:
      ADMIN_USER_PWD:
      BASE_URL:
      SECRET_KEY_BASE:
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
    volumes:
      - geoip:/geoip:ro
